### ISSUE TITLE
Registration of Singletons does not in 1.2.3

### ISSUE THREAD

**Issue by samarthshroff** [AlyElHaddad/ThunderboltIoc#3]
Hi,

I have installed the latest nuget package in my .net framework 4.8 project and created an interface `IAppController` and a concrete class that implements this interface `AppController`.

I have a partial class that inherits from ThunderboltRegistration like this 
![image](https://user-images.githubusercontent.com/22641683/165402267-d601ab23-cf77-4dfb-9fef-e9004d3c1f69.png)

I followed the documentation and wrote the following in the main function
![image](https://user-images.githubusercontent.com/22641683/165402356-60d5f730-0cee-47c8-84ea-e02c7c8832b6.png)

But I get the following error when I run the code 
`Unable to locate a registered implementation for a service of type`

On debugging the code I found out that 
1. the Factory function that is passed to the AddSingletonFactory is assigned to ThunderboltServiceRegistry<T>.RegisteredUserFactory and is passed to the ThunderboltServiceRegistry<T>.Factory function but is never used. Only `dictatedFactory` is used.
2. The `AddSingleton` function also does not make use of the second generic - the TImpl. Just registers the TService.
3. Same is the case with the AddSingleton function that takes in the implSelector function.

The only way (as per the code) to use a singleton right now is to call the Dictate function of ThunderboltContainer.

**Comment by AlyElhaddad** [comment]
The symptoms you're describing seem to align with the hypothesis that the code is not being generated properly. Are you using C# version 9 or later and Visual Studio 2019 16.7 or later?
If not, I suggest you do so.

Regarding your concerns:
1. That is true. However, generated call assigns a value to `dictatedFactory` and it in turn calls the user factory.
2. That is also true. Only generated code takes advantage of the second type parameter.
3. Same.

**Comment by samarthshroff** [comment]
Hi Thank you for the reply. Yes, we are using C# 9.0 with .Net Framework 4.8
![image](https://user-images.githubusercontent.com/22641683/165789276-bb6ddaa1-32a0-4318-85f5-adef1fe771f4.png)
However, we are not using Visual studio, we are using Rider version 2021.3.4
![image](https://user-images.githubusercontent.com/22641683/165789459-80bfb4eb-32a5-492c-a3c5-e517b5150712.png)
Should an IDE be affecting the code generation?

**Comment by AlyElhaddad** [comment]
Yes, the IDE can affect the source generation feature which is vital for this framework. However, to rule out the possibility that the IDE works but code generation fails, please check your build output for the following line:
> Generator '...' failed to generate source. It will not contribute to the output and compilation errors may occur as a result.

If it exists, it's likely that the IDE is okay but the source generator fails; otherwise, it's an IDE issue.

**Comment by AlyElhaddad** [comment]
Also, to better judge, please try the same code-base in Visual Studio 2022 or 2019 version 16.7 (or later).

**Comment by samarthshroff** [comment]
Hi, yes I do get an error 
![image](https://user-images.githubusercontent.com/22641683/165971222-2ad0cfd2-8519-4da2-9dd8-7a3c805f0655.png)

I do have the CodeAnalysis nuget installed for this project
![image](https://user-images.githubusercontent.com/22641683/165971891-9a18f351-197b-453b-92ed-93302fd376c8.png)

I may not have access to Visual Studio. I will have to either make this work with Rider or VSCode. So, is there a way to make the project generate the desired code without using Visual studio?

**Comment by AlyElhaddad** [comment]
The message you shared seems different from the one I suggested. That being said, yes, assuming you have dotnet core installed, you can always go to the project/solution directory in the terminal/command-line and run `dotnet build`. The resulting build output should include the generated code.

Please let me know if that solves the problem.

**Comment by AlyElhaddad** [comment]
Since I have not heard back from you, I will close this issue in the meantime. You can always report any new issues.

**Comment by samarthshroff** [comment]
Okay, Thank you, I will try that, and my apologies I was away and had no access to the internet thus was not able to reply.
